config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login',       to: 'sessions#new'
  post 'login',      to: 'sessions#create'
  delete 'logout',   to: 'sessions#destroy'

  resources :posts, except: [:index, :create]
  get 'posts', to: redirect('/posts/new')
  post 'posts/new', to: 'posts#create'

  resources :users, except: [:index, :create]
  get 'users', to: redirect('/register')
  get 'users/:id/feed', to: 'users#feed', as: 'feed_user'
  get 'users/:id/followers', to: 'users#followers', as: 'followers_user'
  get 'users/:id/following', to: 'users#following', as: 'following_user'
  post 'register', to: 'users#create'
  get 'register',    to: 'users#new'

  resources :follows,  only: [:create, :destroy]

  resources :likes,  only: [:create, :destroy]

  resources :comments, only: [:create, :update]

  resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'password_resets', to: redirect('/password_resets/new')

  root 'sessions#new'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :reset_token
  extend FriendlyId
    friendly_id :nickname, use: [:slugged, :finders]

   has_many :posts, :dependent => :destroy

   has_many :active_follows,      class_name:  "Follow",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
   has_many :passive_follows,     class_name:  "Follow",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy

  has_many :following, through: :active_follows,  source: :followed
  has_many :followers, through: :passive_follows, source: :follower

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :comments, dependent: :destroy


  before_save :downcase_email

  VALID_NAME_REGEX = /\A[a-z0-9\-_]+\z/i
  validates :nickname, presence: true, length: { minimum: 3, maximum: 25 },
                                       uniqueness: { case_sensitive: false },
                                       format: { with: VALID_NAME_REGEX }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, allow_nil: true, length: { maximum: 199 },
                                     format: { with: VALID_EMAIL_REGEX },
                                     uniqueness: { case_sensitive: false }

  validates :password, allow_nil: true, length: { minimum: 6 }
  validates :password_confirmation, allow_nil: true, length: { minimum: 6 }
  has_secure_password

  def downcase_email
    self.email = email.downcase
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = self.following.collect(&:id)
    Post.where(user_id: following_ids)
  end

  def notify_followers(post)
    followers.each do |f|
      f.update_attribute(:notification_count, (f.notification_count + 1))
    end
    send_email_to_followers(post)
  end

  def send_email_to_followers(post)
    followers.where(send_email_acceptance: true).each do |follower|
      UserMailer.notify_user(follower, post).deliver_now
    end
  end

  def clear_notifications
    update_attribute(:notification_count, 0)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def create_reset_digest
    update_attribute(:password_reset_digest,  User.new_token)
    update_attribute(:password_reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    password_reset_sent_at < 2.hours.ago
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show, :edit, :update, :destroy]
  before_action :not_logged_in?, only: [:new, :create]

  #actions for logged in users
  def show
    @user = User.friendly.find(params[:id])
    @posts = @user.posts.order(:created_at).page params[:page]
  end

  #actions to register a account
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome!"
      redirect_to @user
    else
      render 'new'
    end
  end

  #actions for owner of account
  def edit
    @user = User.friendly.find(params[:id])
    if not_owner_check(@user)
      redirect_to current_user
    end
  end

  def update
    @user = User.friendly.find(params[:id])
    if not_owner_check(@user)
      redirect_to current_user
    else
      if @user.update_attributes(user_params)
        flash[:success] = "Success!"
        redirect_to @user
      else
        render 'edit'
      end
    end
  end

  def destroy
    @user = User.friendly.find(params[:id])
    if not_owner_check(@user)
      redirect_to current_user
    else
      @user.destroy
      redirect_to root_path
    end
  end

  def following
    @user = User.friendly.find(params[:id])
    if not_owner_check(@user)
      redirect_to current_user
    else
      @following = @user.following.order(:created_at).page params[:page]
    end
  end

  def followers
    @user = User.friendly.find(params[:id])
    if not_owner_check(@user)
      redirect_to current_user
    else
      @followers = @user.followers.order(:created_at).page params[:page]
    end
  end

  def feed
    @user = User.friendly.find(params[:id])
    if not_owner_check(@user)
      redirect_to current_user
    else
      @user.clear_notifications
      @feed = @user.feed.order(:created_at).page params[:page]
        if !@feed.any?
          @most_recent_posts = Post.all.limit(10)
        end
    end
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :send_email_acceptance,
                                 :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_create_account_form.html.erb
<%= form_for model, url: {action: "create"}, html: {class: 'register'} do |f| %>
  <%= f.label :nickname %><br />
  <%= f.text_field :nickname %><br />

  <%= f.label :email %><br />
  <%= f.email_field :email %><br />

  <%= f.label :password %><br />
  <%= f.password_field :password %><br />

  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %><br />

  <%= f.submit 'Register' %>
<% end %>

app/views/users/_empty_follow.html.erb
<p id="empty_follows"> Empty! :c </p>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_follows.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow" %>
<% end %>

app/views/users/_follow_button.html.erb
<% if current_user != @user %>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
    <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_follows.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow" %>
<% end %>

app/views/users/_user.html.erb
<h2><%= @user.nickname %></h2>
<p> <%= @user.posts.count %> posts!</p>
<%= render 'user_follow' %>

app/views/users/_user_follow.html.erb
<div class='follow'>
  <p>
    <div class='follow_btn'><%= render 'follow_button' %></div>
     <%= @user.followers.count %>
        <% if current_user == @user %>
            <%= link_to 'followers!', followers_user_url(@user) %>
          <% else %>
            followers!
        <% end %>
      <%= @user.following.count %>
        <% if current_user == @user %>
            <%= link_to 'followed!', following_user_url(@user) %>
          <% else %>
            followed!
        <% end %>
  </p>
</div>

app/views/users/_user_posts.html.erb
<%= paginate @posts %>
<% @posts.each do |post| %>
<div class='post'>
  <h3> <%= link_to "#{post.title}", post %> </h3>
  <p> <%= "#{pluralize(post.likes.count, 'like')}!"%><p>
</div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'User Settings') %>
<div class='create_form'>
  <%= render partial: 'shared/errors', locals: {model: @user} %>
  <%= form_for @user, url: {action: "update"} do |f| %>

    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %><br />

    <%= f.label "Get Emails" %>
    <%= f.check_box :send_email_acceptance, {}, true, false %> <br />

    <%= f.button :Submit %>
  <% end %>

</div>

<div class="delete_form">
<p> Delete account: </p>
<%= link_to "DELETE", @user, method: :delete,
                                 data: { confirm: "You sure? :c"} %>
</div>

app/views/users/feed.html.erb
<% provide(:title, 'Feed') %>
<% if @feed.any? %>
  <div class="feed">
  <h4> Followed user's posts:</h4>
  <%= paginate @feed %>
    <% @feed.each do |post| %>
      <p> <%= link_to "#{post.title}", post %>,
       by <%= link_to "#{post.user.nickname}", post.user%></p>
    <% end %>
  </div>
<% else %>
    <%= render 'empty_feed' %>
<% end %>

app/views/users/followers.html.erb
<% provide(:title, 'Followers') %>
<div class="followers_and_followed">
  <h3> Followers </h3>
    <ul>
    <%= paginate @followers %>
    <% @followers.each do |user| %>
      <li><%= link_to "#{user.nickname}", user %>
    <% end %>
    </ul>
</div>
<%= render 'empty_follow' if @followers.empty? %>

app/views/users/following.html.erb
<% provide(:title, 'Following') %>
<div class="followers_and_followed">
  <h3> Followed: </h3>
  <ul>
    <%= paginate @following %>
    <% @following.each do |user| %>
      <li><%= link_to "#{user.nickname}", user %></li>
    <% end %>
  </ul>
</div>
<%= render 'empty_follow' if @following.empty? %>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<div class= "create_form">
  <h2> Welcome! Register yourself... </h2>
  <%= render partial: 'shared/errors', locals: {model: @user} %>
  <%= render partial: 'create_account_form', locals: {model: @user} %>
  <h3> or maybe you <%= link_to 'have a account?', login_path %></h3>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.nickname}") %>
<div class="user"><%= render 'user' %></div>
<h2>
  <%= (link_to 'Create new post!', new_post_path) if @user == current_user %>
</h2>
<div class="user_posts"><%= render 'user_posts' %></div>