config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login',       to: 'sessions#new'
  post 'login',      to: 'sessions#create'
  delete 'logout',   to: 'sessions#destroy'

  resources :posts, except: [:index, :create]
  get 'posts', to: redirect('/posts/new')
  post 'posts/new', to: 'posts#create'

  resources :users, except: [:index, :create]
  get 'users', to: redirect('/register')
  get 'users/:id/feed', to: 'users#feed', as: 'feed_user'
  get 'users/:id/followers', to: 'users#followers', as: 'followers_user'
  get 'users/:id/following', to: 'users#following', as: 'following_user'
  post 'register', to: 'users#create'
  get 'register',    to: 'users#new'

  resources :follows,  only: [:create, :destroy]

  resources :likes,  only: [:create, :destroy]

  resources :comments, only: [:create, :update]

  resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'password_resets', to: redirect('/password_resets/new')

  root 'sessions#new'
end

app/views/layouts/_footer.html.erb
<div class="footer">
<p> Created by <%= link_to 'B3v3', 'https://github.com/B3v3'%> </p>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  Blog-for-you-site
<%  if current_user %>
  <div class ="header-right">
    <%= (link_to "#{current_user.nickname}", current_user)%>   |
    <%= (link_to  " Feed(#{current_user.notification_count})",
                   feed_user_url(current_user)) %>             |
    <%= (link_to 'Settings', edit_user_path(current_user))%>   |
    <%= (link_to ' Logout', logout_path, method: :delete)%>
  </div>  
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <div class="alert-<%= key %>"><%= value %></div>
    <% end %>
    
    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>